export const GET_CARS_REQUEST = 'GET_CARS_REQUEST';
export const GET_CARS_SUCCESS = 'GET_CARS_SUCCESS';
export const GET_CARS_FAILED = 'GET_CARS_FAILED';
export const GET_CAR_TYPES_REQUEST = 'GET_CAR_TYPES_REQUEST';
export const GET_CAR_TYPES_SUCCESS = 'GET_CAR_TYPES_SUCCESS';
export const GET_CAR_TYPES_FAILED = 'GET_CAR_TYPES_FAILED';
export const APPEND_RELATIONSHIPS_IN_CARS = 'APPEND_RELATIONSHIPS_IN_CARS'
