//Types of action.
export const GET_INDIVIDUALS_REQUEST = 'GET_INDIVIDUALS_REQUEST';
export const GET_INDIVIDUALS_SUCCESS = 'GET_INDIVIDUALS_SUCCESS';
export const GET_INDIVIDUALS_FAILED = 'GET_INDIVIDUALS_FAILED';
