"""Initial

Revision ID: 31e5199abae7
Revises: 
Create Date: 2017-02-13 14:22:48.461447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31e5199abae7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('individuals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('driver_license', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('car_type', sa.Integer(), nullable=True),
    sa.Column('registration_number', sa.String(length=40), nullable=True),
    sa.Column('consumption_norm_distance', sa.Integer(), nullable=True),
    sa.Column('consumption_norm_hours', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['car_type'], ['cartypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waybills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('consumption_fact', sa.Float(), nullable=True),
    sa.Column('consumption_norm', sa.Float(), nullable=True),
    sa.Column('mileage_begin', sa.Float(), nullable=True),
    sa.Column('mileage_end', sa.Float(), nullable=True),
    sa.Column('mileage_time_hour', sa.Integer(), nullable=True),
    sa.Column('mileage_time_min', sa.Integer(), nullable=True),
    sa.Column('_activate', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['individuals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waybills')
    op.drop_table('cars')
    op.drop_table('individuals')
    op.drop_table('cartypes')
    # ### end Alembic commands ###
