"""Restruct waybill

Revision ID: fea452664a18
Revises: 8cbc20b2d8cf
Create Date: 2017-02-16 16:24:35.337299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fea452664a18'
down_revision = '8cbc20b2d8cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waybills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departure_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('mileage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('return_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('run_time', sa.Integer(), nullable=True))
        batch_op.drop_column('mileage_time_hour')
        batch_op.drop_column('mileage_time_min')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waybills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mileage_time_min', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('mileage_time_hour', sa.INTEGER(), nullable=True))
        batch_op.drop_column('run_time')
        batch_op.drop_column('return_time')
        batch_op.drop_column('mileage')
        batch_op.drop_column('departure_time')

    # ### end Alembic commands ###
